name: pytest

on:
  push:
    branches:
      - main  # Ou remplacez par le nom de votre branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.5"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assurez-vous de remplacer `requirements.txt` par le fichier contenant vos dépendances

      - name: Analyzing the code with pytest
        run: |
          pytest $(git ls-files 'test_*.py')  # Assurez-vous que cette commande est correcte et correspond à vos besoins
